DocSite/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DocSite.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

    }
}

DocSite/ViewModels/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DocSite.ViewModels
{
    public class ProductViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

DocSite/Controllers/API/DocumentsApiController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using System.Data.Entity;
using DocSite.Models;
using Microsoft.AspNet.Identity;

namespace DocSite.Controllers.Api
{
    public class DocumentsController : ApiController
    {
        private ApplicationDbContext _context;
        private BaseController baseController;

        public DocumentsController()
        {
            _context = new ApplicationDbContext();
            baseController = new BaseController();
        }

        [Route("api/documentsapi/getdocuments/{id}")]
        [HttpGet]
        public IHttpActionResult GetDocuments(int id)
        {

            List<Document> documents = new List<Document>();

            string organization = "";

            var documentsInDbByProductId = _context.Documents.Where(d => d.ProductId == id).ToList();
            if (documentsInDbByProductId.Any()) //ei ole koskaan null => katsotaan onko yhtään tulosta
            {
                try
                {
                    var authorId = User.Identity.GetUserId();
                    organization = baseController.GetOrganizationByAuthorId(authorId);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.StackTrace);
                }

                foreach (var document in documentsInDbByProductId)
                {
                    //document Ids by product in organizations datatable
                    var docsByProductInOrganizationsDb = _context.Organizations
                        .Where(o => o.DocumentID == document.DocumentID);

                    //check if document is authorized for logged in user or document is "public" and all users
                    if (docsByProductInOrganizationsDb.Any())
                    {
                        foreach (var org in docsByProductInOrganizationsDb)
                        {
                            if (org.Name == organization || org.Name == "Public")
                                documents.Add(documentsInDbByProductId
                                    .SingleOrDefault(d => d.DocumentID == org.DocumentID));
                        }
                    }
                }
            }
            return Ok(documents);
        }

        [Route("api/documentsapi/getorganizationdocuments/{organization}")]
        [HttpGet]
        public IHttpActionResult GetOrganizationDocuments(string organization)
        {
            List<Document> documents = new List<Document>();

            //Documents where productId == 0 = organizational documents
            var documentsInDb = _context.Documents.Where(d => d.ProductId == 0).ToList();

            if (documentsInDb.Any())
            {
                foreach (var document in documentsInDb)
                {
                    //document Ids by product in organizations datatable
                    var docsInOrganizationsDb = _context.Organizations
                        .Where(o => o.DocumentID == document.DocumentID);

                    //check if document is authorized for logged in user or document is "public" and all users
                    foreach (var org in docsInOrganizationsDb)
                    {
                        if (docsInOrganizationsDb.Any() && org.Name == organization)
                            documents.Add(document);
                    }
                }
            }
            return Ok(documents);
        }

        [HttpDelete]
        public IHttpActionResult DeleteDocument(int id)
        {
            var documentInDb = _context.Documents.SingleOrDefault(d => d.Id == id);

            if (documentInDb == null)
                return NotFound();

            /*_context.Documents.Remove(documentInDb);
            _context.SaveChanges();
            File.Delete(documentInDb.FilePath);

            return Ok();*/


            var organization = baseController.GetOrganizationByAuthorId(User.Identity.GetUserId());
            var documentsInOrganizationsDb = _context.Organizations.Where(d => d.DocumentID == documentInDb.DocumentID);

            Organization found = new Organization();

            if (documentsInOrganizationsDb.Any())
                found = documentsInOrganizationsDb.FirstOrDefault(x => x.Name == organization || x.Name == "Public");

            var documentsRemaining = documentsInOrganizationsDb.ToList();
            documentsRemaining.Remove(found);

            if(found.Name == "Public" && organization == "Timehouse")
            {
                _context.Organizations.Remove(found);
                if (!documentsRemaining.Any())
                {
                    _context.Organizations.Remove(found);
                    _context.Documents.Remove(documentInDb);
                }
                _context.SaveChanges();
                try
                {
                    File.Delete(found.FilePath);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
            }

            else if (found != null && found.Name != "Public")
            {
                _context.Organizations.Remove(found);
                if (!documentsRemaining.Any())
                {
                    _context.Organizations.Remove(found);
                    _context.Documents.Remove(documentInDb);
                }
                _context.SaveChanges();
                try
                {
                    File.Delete(found.FilePath);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }

            }
            else
                return BadRequest();


            return Ok();
        }

    }
}

DocSite/Controllers/ProductsController.cs
using DocSite.Models;
using DocSite.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace DocSite.Controllers
{
    public class ProductsController : BaseController
    {

        public ProductsController()
        {
            _context = new ApplicationDbContext();
           
        }

        // GET: Product
        public ActionResult Index()
        {
            var userOrg = GetOrganizationByAuthorId(User.Identity.GetUserId());
            List<Product> products = _context.Products.ToList();

            var viewModel = new ProductOrgViewModel
            {
                Organization = userOrg,
                Products = products
            };

            return View("Index", viewModel);
        }

    }
}

DocSite/Views/Products/Index.cshtml
@model DocSite.ViewModels.ProductOrgViewModel
@{
    ViewBag.Title = DocSite.Resources.Resources.Home;
}
<html xmlns="http://www.w3.org/1999/xhtml">
<body class="home-content" style="background-color:white">
    <div class="widthlimit">
        <div class="menuleft">
            <h2>
                <a>@DocSite.Resources.Documents.Navigation</a>
            </h2>
            <div class="menuleft_item">
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink(Model.Organization, "Organization", "Documents")
                }
                @foreach (var product in Model.Products)
                {
                    if (product.Name == "Solutions")
                    {

                        <a href="" class="productClick" data-product-id=@product.Id>@DocSite.Resources.Documents.Solutions</a>
                    }
                    else
                    {
                        <a href="" class="productClick" data-product-id=@product.Id>@product.Name</a>
                    }
                }

                }
            </div>
        </div>
        <span id="scroll_to_content_anchor"></span>
        <div class="page-container">
            <div class="page-boxtitle box-green">
                <h1 class="aineistopankki-h1">@DocSite.Resources.Resources.MaterialBank</h1>
                <p>@DocSite.Resources.Resources.MaterialBankInfo</p>
            </div>

            <!--
            <p>Timehouse tarjoaa asiakkailleen kattavan valikoiman palveluja.</p>
            -->

            @foreach (var product in Model.Products)
            {
                var picPath = "/Pictures/" + product.Name + ".png";
                if (product.Id % 2 != 0)
                {
                    <div>
                        <div style="float:left;width:50%;">
                            <a data-product-id=@product.Id class="productClick product-btn product-btn-left">
                                <span style="display:block;margin:0;height:20px;overflow:visible;color:#ffffff;">@product.Name</span>
                                <span style="display:block;text-align:center;padding-left:15%;padding-right:15%;padding-top: 4%;">
                                    <img src=@picPath alt="" style="width:100%;height:auto;">
                                </span>
                            </a>
                        </div>
                    </div>

                }
                else
                {
                    if (product.Name == "Solutions")
                    {
                        <div>
                            <div style="float:left;width:50%;">
                                <a style="background:rgba(105, 95, 79, 0.8);" class=" productClick product-btn product-btn-right" data-product-id="4">
                                    <span style="display:block;margin:0;height:20px;overflow:visible;color:#ffffff;">@DocSite.Resources.Documents.Solutions</span>
                                        <h1 class="solutions-txt" style="font-size:2.5em;color:#fff;font-family:CoolV,Arial,Sans-serif;font-weight:normal">@DocSite.Resources.Documents.Solutions</h1>
                                </a>

                            </div>
                        </div>
                    }
                    else
                    {
                        <div>
                            <div style="float:left;width:50%;">
                                <a data-product-id=@product.Id class=" productClick product-btn product-btn-right">
                                    <span style="display:block;margin:0;height:20px;overflow:visible;color:#ffffff;">@product.Name</span>
                                    <span class="productimg">
                                        <img src=@picPath alt="" style="width:100%;height:auto;">
                                    </span>
                                </a>
                            </div>
                        </div>
                    }
                }
            }
        </div>
    </div>
</body>
</html>


@section scripts
    {
    <script>
        $(document).ready(function () {
            $(".productClick").on("click", function (e) {
                e.preventDefault();
                var button = $(this);
                var url = "/documents/index/" + button.attr("data-product-id");
                window.location.href = url;
            });
        });
    </script>
}